// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatus string

const (
	AccountStatusActive              AccountStatus = "active"
	AccountStatusSuspended           AccountStatus = "suspended"
	AccountStatusFrozen              AccountStatus = "frozen"
	AccountStatusPendingVerification AccountStatus = "pending_verification"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type DepositCurrency string

const (
	DepositCurrencyUSDT DepositCurrency = "USDT"
)

func (e *DepositCurrency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DepositCurrency(s)
	case string:
		*e = DepositCurrency(s)
	default:
		return fmt.Errorf("unsupported scan type for DepositCurrency: %T", src)
	}
	return nil
}

type NullDepositCurrency struct {
	DepositCurrency DepositCurrency `json:"deposit_currency"`
	Valid           bool            `json:"valid"` // Valid is true if DepositCurrency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDepositCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.DepositCurrency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DepositCurrency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDepositCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DepositCurrency), nil
}

type DividendStatus string

const (
	DividendStatusPending DividendStatus = "pending"
	DividendStatusPaid    DividendStatus = "paid"
	DividendStatusFailed  DividendStatus = "failed"
)

func (e *DividendStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DividendStatus(s)
	case string:
		*e = DividendStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DividendStatus: %T", src)
	}
	return nil
}

type NullDividendStatus struct {
	DividendStatus DividendStatus `json:"dividend_status"`
	Valid          bool           `json:"valid"` // Valid is true if DividendStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDividendStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DividendStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DividendStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDividendStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DividendStatus), nil
}

type RateLockStatus string

const (
	RateLockStatusActive    RateLockStatus = "active"
	RateLockStatusExpired   RateLockStatus = "expired"
	RateLockStatusUsed      RateLockStatus = "used"
	RateLockStatusCancelled RateLockStatus = "cancelled"
)

func (e *RateLockStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RateLockStatus(s)
	case string:
		*e = RateLockStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RateLockStatus: %T", src)
	}
	return nil
}

type NullRateLockStatus struct {
	RateLockStatus RateLockStatus `json:"rate_lock_status"`
	Valid          bool           `json:"valid"` // Valid is true if RateLockStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRateLockStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RateLockStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RateLockStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRateLockStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RateLockStatus), nil
}

type TransactionStatus string

const (
	TransactionStatusDepositPending TransactionStatus = "deposit_pending"
	TransactionStatusQuoteLocked    TransactionStatus = "quote_locked"
	TransactionStatusConfirming     TransactionStatus = "confirming"
	TransactionStatusPayingOut      TransactionStatus = "paying_out"
	TransactionStatusSwapping       TransactionStatus = "swapping"
	TransactionStatusSlippageReview TransactionStatus = "slippage_review"
	TransactionStatusCompleted      TransactionStatus = "completed"
	TransactionStatusExpired        TransactionStatus = "expired"
	TransactionStatusFailed         TransactionStatus = "failed"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type TransactionType string

const (
	TransactionTypeSwap TransactionType = "swap"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type WebhookStatus string

const (
	WebhookStatusPending   WebhookStatus = "pending"
	WebhookStatusProcessed WebhookStatus = "processed"
	WebhookStatusFailed    WebhookStatus = "failed"
)

func (e *WebhookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookStatus(s)
	case string:
		*e = WebhookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookStatus: %T", src)
	}
	return nil
}

type NullWebhookStatus struct {
	WebhookStatus WebhookStatus `json:"webhook_status"`
	Valid         bool          `json:"valid"` // Valid is true if WebhookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookStatus), nil
}

type WithdrawalCurrency string

const (
	WithdrawalCurrencyNGN WithdrawalCurrency = "NGN"
)

func (e *WithdrawalCurrency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WithdrawalCurrency(s)
	case string:
		*e = WithdrawalCurrency(s)
	default:
		return fmt.Errorf("unsupported scan type for WithdrawalCurrency: %T", src)
	}
	return nil
}

type NullWithdrawalCurrency struct {
	WithdrawalCurrency WithdrawalCurrency `json:"withdrawal_currency"`
	Valid              bool               `json:"valid"` // Valid is true if WithdrawalCurrency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWithdrawalCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.WithdrawalCurrency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WithdrawalCurrency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWithdrawalCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WithdrawalCurrency), nil
}

type RateLocks struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CryptoAmount   pgtype.Numeric     `json:"crypto_amount"`
	CryptoCurrency DepositCurrency    `json:"crypto_currency"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       WithdrawalCurrency `json:"currency"`
	Rate           pgtype.Numeric     `json:"rate"`
	Status         RateLockStatus     `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ReferralDividends struct {
	ID             pgtype.UUID        `json:"id"`
	ReferrerID     pgtype.UUID        `json:"referrer_id"`
	ReferredUserID pgtype.UUID        `json:"referred_user_id"`
	TransactionID  pgtype.UUID        `json:"transaction_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       WithdrawalCurrency `json:"currency"`
	Status         DividendStatus     `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Transactions struct {
	ID                      pgtype.UUID        `json:"id"`
	UserID                  pgtype.UUID        `json:"user_id"`
	RateLockID              pgtype.UUID        `json:"rate_lock_id"`
	DepositWalletAddress    string             `json:"deposit_wallet_address"`
	CryptoAmount            pgtype.Numeric     `json:"crypto_amount"`
	TxHash                  pgtype.Text        `json:"tx_hash"`
	NetworkConfirmations    pgtype.Int4        `json:"network_confirmations"`
	CryptoCurrency          DepositCurrency    `json:"crypto_currency"`
	AmountToReceiveCurrency WithdrawalCurrency `json:"amount_to_receive_currency"`
	AmountToReceive         pgtype.Numeric     `json:"amount_to_receive"`
	Fee                     pgtype.Int8        `json:"fee"`
	PlatformFee             pgtype.Int8        `json:"platform_fee"`
	YellowCardOrderID       pgtype.Text        `json:"yellow_card_order_id"`
	YellowCardStatus        pgtype.Text        `json:"yellow_card_status"`
	PaystackTransferCode    pgtype.Text        `json:"paystack_transfer_code"`
	PaystackTransferStatus  pgtype.Text        `json:"paystack_transfer_status"`
	TransactionType         TransactionType    `json:"transaction_type"`
	Status                  TransactionStatus  `json:"status"`
	FailureReason           pgtype.Text        `json:"failure_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Users struct {
	ID            pgtype.UUID       `json:"id"`
	Nationality   string            `json:"nationality"`
	PhoneNumber   pgtype.Text       `json:"phone_number"`
	Name          string            `json:"name"`
	Email         string            `json:"email"`
	PasswordHash  string            `json:"password_hash"`
	DateOfBirth   pgtype.Date       `json:"date_of_birth"`
	Bvn           pgtype.Text       `json:"bvn"`
	PhoneVerified pgtype.Bool       `json:"phone_verified"`
	EmailVerified pgtype.Bool       `json:"email_verified"`
	KycVerified   pgtype.Bool       `json:"kyc_verified"`
	AccountStatus NullAccountStatus `json:"account_status"`
	CreatedAt     pgtype.Timestamp  `json:"created_at"`
	UpdatedAt     pgtype.Timestamp  `json:"updated_at"`
	ReferralCode  pgtype.Text       `json:"referral_code"`
	ReferredBy    pgtype.UUID       `json:"referred_by"`
}

type Webhooks struct {
	ID           pgtype.UUID        `json:"id"`
	Provider     string             `json:"provider"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	Status       WebhookStatus      `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
