// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateUserOnSignup(ctx context.Context, arg CreateUserOnSignupParams) (Users, error)
	FindUserByEmail(ctx context.Context, email string) (Users, error)
}

var _ Querier = (*Queries)(nil)
