// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserOnSignup = `-- name: CreateUserOnSignup :one
INSERT INTO users(
    nationality,
    phone_number,
    name,
    email,
    password_hash
)
VALUES(
    $1, $2, $3, $4, $5
)
RETURNING id, nationality, phone_number, name, email, password_hash, date_of_birth, bvn, phone_verified, email_verified, kyc_verified, account_status, created_at, updated_at, referral_code, referred_by
`

type CreateUserOnSignupParams struct {
	Nationality  string      `json:"nationality"`
	PhoneNumber  pgtype.Text `json:"phone_number"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateUserOnSignup(ctx context.Context, arg CreateUserOnSignupParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUserOnSignup,
		arg.Nationality,
		arg.PhoneNumber,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Nationality,
		&i.PhoneNumber,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.DateOfBirth,
		&i.Bvn,
		&i.PhoneVerified,
		&i.EmailVerified,
		&i.KycVerified,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralCode,
		&i.ReferredBy,
	)
	return i, err
}
